[theme]
base = "light"
primaryColor = "#4a88d0"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#222831"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
